services:
    itchygeek:
        container_name: itchygeek
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - SSL_PATH=${SSL_PATH:-./nginx/certs}
        ports:
            - '80:80'
            - '443:443'
