# unique project key in SonarQube
sonar.projectKey=itchygeek
sonar.projectName=Itchygeek
sonar.projectVersion=1.0

# point to your source code
sonar.sources=src

# ignore build and deps
sonar.exclusions=**/node_modules/**,build/**,public/**

# encoding
sonar.sourceEncoding=UTF-8

# (optional) include your coverage report
# run `npm test -- --coverage` first, then uncomment:
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
