name: Deploy project

on:
    push:
        branches:
            - main

jobs:
    sonar:
        name: SonarQube Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Java 11
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: '11'

            - name: Run SonarQube scanner
              env:
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                  SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }
              run: |
                  # install the CLI  
                  wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
                  unzip sonar-scanner-cli-4.8.0.2856-linux.zip
                  export PATH="$PWD/sonar-scanner-4.8.0.2856-linux/bin:$PATH"

                  # run the analysis
                  sonar-scanner \
                    -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
                    -Dsonar.sources=src \
                    -Dsonar.host.url="$SONAR_HOST_URL" \
                    -Dsonar.login="$SONAR_LOGIN"

    deploy:
        name: Deploy to Production
        needs: sonar
        if: ${{ needs.sonar.result == 'success' }}
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  node-version: 22

            - name: Setup SSH Key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Create .env file
              run: |
                  echo "SSL_PATH=${{vars.SSL_CERT_PATH}}" > .env
                  cat .env

            - name: Cleanup existing files
              run: |
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
                  rm -rf ${{vars.SSH_PATH}}/{*,.*} 2>/dev/null || true"

            - name: Deploy using SCP
              run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -r . ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{vars.SSH_PATH}}

            - name: Restart server
              run: |
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
                  cd ${{vars.SSH_PATH}} && \
                  docker-compose down && docker-compose up --force-recreate --build -d"

            - name: Cleanup after deployment
              run: |
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "
                  rm -rf ${{vars.SSH_PATH}}/{*,.*} 2>/dev/null || true"
