name: Deploy project

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - uses: actions/checkout@v2
              with:
                  node-version: 22
            - name: Install dependencies
              run: yarn
            - name: Build project
              run: yarn build
            - name: Get SSH key and set permissions
              run: |
                  mkdir -p ~/.ssh
                  echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
            - name: Deploy using SCP
              run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.SSH_PATH}}
            - name: Restart server
              run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.SSH_PATH}} && docker-compose down && docker-compose up -d"
