name: Test project

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - uses: actions/checkout@v2
              with:
                  node-version: 22
            - name: Install dependencies
              run: yarn
